/**
 * One-off: self-host the three default Google fonts. Fetches the Google CSS,
 * keeps only the latin + latin-ext subsets, downloads those woff2 files into
 * public/fonts/, and writes public/fonts/fonts.css with rewritten URLs.
 *
 * Run: node scripts/fetch-fonts.mjs   (re-run only if the default fonts change)
 */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext']);
const OUT = new URL('../public/fonts', import.meta.url).pathname;
mkdirSync(OUT, { recursive: true });

const FAMILIES = [
  { name: 'Spectral', slug: 'spectral', url: 'https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,400;0,500;0,600;1,400&display=swap' },
  { name: 'Hanken Grotesk', slug: 'hanken', url: 'https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600&display=swap' },
  { name: 'IBM Plex Mono', slug: 'ibmplexmono', url: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap' },
];

function curl(url, binary = false) {
  const flags = binary ? '-sSL --output -' : '-sSL';
  return execSync(`curl ${flags} -A '${UA}' '${url}'`, { maxBuffer: 64 * 1024 * 1024, encoding: binary ? 'buffer' : 'utf8' });
}

const out = [];
const downloaded = new Set();

for (const fam of FAMILIES) {
  const css = curl(fam.url);
  // Each subset block is preceded by a /* subset */ comment.
  const blocks = css.split(/\/\*\s*/).slice(1); // ["latin */\n@font-face{...}", ...]
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf(' ')).trim();
    if (!KEEP.has(subset)) continue;
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
    const style = /font-style:\s*italic/.test(block) ? 'italic' : 'normal';
    const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';
    const srcUrl = (block.match(/src:\s*url\(([^)]+)\)/) || [])[1];
    if (!srcUrl) continue;
    const fname = `${fam.slug}-${weight}${style === 'italic' ? 'i' : ''}-${subset}.woff2`;
    if (!downloaded.has(fname)) {
      const buf = curl(srcUrl, true);
      writeFileSync(join(OUT, fname), buf);
      downloaded.add(fname);
      console.log(`${fname}  (${(buf.length / 1024).toFixed(1)} KB)`);
    }
    out.push(
      `@font-face {\n  font-family: '${fam.name}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url(/fonts/${fname}) format('woff2');\n  unicode-range: ${range.trim()};\n}`
    );
  }
}

writeFileSync(join(OUT, 'fonts.css'), `/* Self-hosted default fonts — generated by scripts/fetch-fonts.mjs */\n${out.join('\n')}\n`);
console.log(`\nWrote public/fonts/fonts.css (${out.length} @font-face rules)`);
